### PR TITLE
Cleanup urls in csv

### PR DESCRIPTION
**Pull request by igorbrigadir**
Cleaned up a few urls & filled in a few missing ones in /db/data/candidates.csv 

- Replaced urls that redirect
- Replaced linkedin, fb, twitter urls with canonical profile urls
- Removed unnecessary parameters from urls
- Some website urls were in email column, facebook links in twitter column, etc.

It looks like it was parsed & cleaned up later on http://irish-elections.storyful.com/candidates.csv but I needed a cleaner csv with urls, and these changes are here if you want. Not sure if changes break anything! Haven't tested the code - so feel free to close.

### CODE REVIEW

**Comment by JonMidhir** [comment]
Hi Igor,

Thanks for the submission!

I'm delaying on merging the PR because we use `rake db:seed` to repopulate the database from this CSV file, and changing to tab-separated values will break this import. We replace this CSV periodically by exporting from a Google spreadsheet, so your changes would be overwritten unless we include them in the spreadsheet.

I can't see the actual diffs of what you changed but your work on URLs would be really useful to us if we could include it.

cc/ @giannileggio @shaicoleman @mmarignoli @tonybyrne

**Comment by igorbrigadir** [comment]
Oops! I seem to have mangled the commas & tabs...

I'll close this one and have a look at a better way to include the URL cleaning steps. While some were manually fixed, majority were just following redirects to canonical url & stripped of extra parameters.

Another cleaning step I left out, but might be useful: Normalizing phone numbers with this thing: https://github.com/googlei18n/libphonenumber

If it works for you, I can add my changes to the Google Spreadsheet? igor.brigadir@gmail.com if you need a google account.

**Comment by JonMidhir** [comment]
@igorbrigadir 

Thanks, please don't muck your changes though - we can use them!

I'll get in touch with the journalists who were handling the data import and get them to get in touch.

We're currently using a great gem called `phoney_rails` to normalise phone numbers when they're imported. Will check out libphonenumber for sure.

**Comment by igorbrigadir** [comment]
Great! You should be able to see them now:

Original:
https://github.com/storyful/irish-elections/blob/master/db/data/candidates.csv

Edits:
https://github.com/igorbrigadir/irish-elections/blob/data-clean/db/data/candidates.csv

**Comment by tonybyrne** [comment]
Hi Igor,

Just a note to say thanks for chipping in! I trust all is well with you?

Tony

**Comment by igorbrigadir** [comment]
All's well on the Insight front, Thanks! 

Gonna close this and open up an issue with corrections & updates, according to this: http://adriankavanaghelections.org/2014/10/22/officially-declared-candidates-for-the-20152016-general-election/ there are now 429 candidates.

**Pull request closed without merging**
